### ISSUE TITLE
C pre-processor error in Hit.hs

### ISSUE THREAD

**Issue by ipuustin** [vincenthz/hit#26]
There appars to be a build issue with Hit.hs:

```
$ runhaskell Hit/Hit.hs

Data/Git/Storage/Object.hs:63:0:
     error: missing binary operator before token "("
     #if MIN_VERSION_bytestring(0,10,0)
     ^
phase `C pre-processor' failed (exitcode = 1)
```

**Comment by vincenthz** [comment]
it would help to run `runhaskell` in the `Hit` directory, otherwise runhaskell is going try to recompile stuff it shouldn't, like `Data.Git.Storage.Object`. If that doesn't though, I'm not sure how useful it is to use runhaskell on hit.

**Comment by vincenthz** [comment]
If it still doesn't works and that you have a specific use case, don't hesitate to open a new issue.
